### ISSUE TITLE
Karma test run doesn't work. Does not import @material/* packages properly.

### ISSUE THREAD

**Issue by dragoscirjan** [dragoscirjan/aurelia-material-components-web#1]
**I'm submitting a bug report**

```bash
karma run #leads to

5 2018 22:03:21.345:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
02 05 2018 22:03:21.346:INFO [launcher]: Launching browser Chrome with unlimited concurrency
02 05 2018 22:03:21.350:INFO [launcher]: Starting browser Chrome
02 05 2018 22:03:22.943:INFO [Chrome 66.0.3359 (Windows 10.0.0)]: Connected on socket BeWNgwVhsW6W1_ZJAAAA with id 61205406
Chrome 66.0.3359 (Windows 10.0.0) ERROR
  Error: (SystemJS) Unexpected token *
        SyntaxError: Unexpected token *
            at eval (<anonymous>)
            at Object.eval (jspm_packages/npm/@material/drawer@0.35.0.js:1:123)
            at eval (jspm_packages/npm/@material/drawer@0.35.0.js:2:4)
            at eval (jspm_packages/npm/@material/drawer@0.35.0.js:3:3)
        Evaluating jspm_packages/npm/@material/drawer@0.35.0/index.js
        Evaluating jspm_packages/npm/@material/drawer@0.35.0.js
        Evaluating src/drawer.js
        Evaluating src/index.js
        Evaluating test/unit/configure.spec.js
        Error loading test/unit/configure.spec.js
```

**Comment by dragoscirjan** [comment]
Migrated to karma-webpack and addapted code to run with webpack.
